resources:
  - name: myDockerRepo
    type: GitRepo
    configuration:
      gitProvider: myGitHub
      path: tsuyo/MySourceRepo     # Replace with your Git repo  
    branches:
        include: master
 
  - name: build_info_1_docker_build_push
    type: BuildInfo
    configuration:
      sourceArtifactory: myArtifactory
      buildName: svc_build
      buildNumber: 1

pipelines:
  - name: pipeline_docker_build_push
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dockerGroup
          dockerFileLocation: docker-build
          dockerFileName: Dockerfile
          dockerImageName: 'artifactory1.tsuyo.org:8081/docker-local/myscratch'
          dockerImageTag: ${run_number}
          inputResources:
            - name: myDockerRepo
          integrations:
            - name: myArtifactory
 
      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dockerGroup
          targetRepository: docker-local
          integrations:
            - name: myArtifactory
          inputSteps:
            - name: docker_build
 
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_1_docker_build_push
